name = "subgraph-ts-worker"
type = "javascript"
zone_id = ""
workers_dev = true
compatibility_date = "2022-01-05"

kv_namespaces = [ 
	 { id="ca8261299da44e95a5f013f662732d2e", binding = "HEALTHS", preview_id = "1d9d958a59c546b7b79ada85ffb45699" },

]
webpack_config = "webpack.config.js"



[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"


