name = "subgraph-health-update-cron"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-01-05"

# kv_namespaces = [ 
# 	 { id="***", binding = "HEALTHS", preview_id = "***" },
# ]
webpack_config = "webpack.config.js"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"


